version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: nook-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nook_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d nook_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: nook-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"

  app:
    build: .
    container_name: nook-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MINIO_HOST: minio
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      ACCESS_SECURITY_KEY: ${ACCESS_SECURITY_KEY}
      REFRESH_SECURITY_KEY: ${REFRESH_SECURITY_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe_cli
    command: >
      listen
      --api-key ${STRIPE_SECRET_KEY}
      --forward-to app:8080/api/stripe-notifications
      --skip-verify
    environment:
      STRIPE_API_KEY: ${STRIPE_SECRET_KEY}
    depends_on:
      - app