spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nook_test_db
    username: test_user
    password: test_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    locations: classpath:db/migration