spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/nook_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
  flyway:
    enabled: true
  security:
    secret-key: ${SECURITY_KEY:Wm85F524PED7mf2-EbwfUuGV96u6a5HxSaa4nZXI98A}
    expiration: 3600000

minio:
  url: http://${MINIO_HOST:localhost}:9000
  access-key: ${MINIO_ACCESS_KEY:minio}
  secret-key: ${MINIO_SECRET_KEY:minio123}
  bucket: ${MINIO_BUCKET:listing-images}

app:
  booking:
    cancellation-window-days: 2