spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/nook_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
  flyway:
    enabled: true
  security:
    secret-key: ${SECURITY_KEY}
    expiration: 3600000

minio:
  url: http://${MINIO_HOST:localhost}:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

app:
  booking:
    cancellation-window-days: 2

stripe:
  api:
    secret-key: ${STRIPE_SECRET_KEY}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}